// File automatically generated by Parser/asdl_c.py.

#define TRAVERSE(TYPE, NODE) { \
    if ((NODE)) { \
        result = traverse ## TYPE((NODE), tag, flag); \
        if (*flag) { \
            return NULL; \
        } else if (result) { \
            return result; \
        } \
    } \
}

#define TRAVERSE_SEQ(TYPE, SEQ) { \
    for (_i = 0; _i < asdl_seq_LEN((SEQ)); _i++) { \
        TYPE ## _ty elt = (TYPE ## _ty)asdl_seq_GET((SEQ), _i); \
        TRAVERSE((TYPE), elt); \
    } \
}
void *
find_comprehension(comprehension_ty node, int tag, int *flag)
    int _i = 0;
    void *result = NULL;
    TRAVERSE(expr, node->target);
    TRAVERSE(expr, node->iter);
    TRAVERSE_SEQ(expr, node->ifs);
    TRAVERSE(int, node->is_async);
{
}
void *
find_arguments(arguments_ty node, int tag, int *flag)
    int _i = 0;
    void *result = NULL;
    TRAVERSE_SEQ(arg, node->posonlyargs);
    TRAVERSE_SEQ(arg, node->args);
    TRAVERSE(arg, node->vararg);
    TRAVERSE_SEQ(arg, node->kwonlyargs);
    TRAVERSE_SEQ(expr, node->kw_defaults);
    TRAVERSE(arg, node->kwarg);
    TRAVERSE_SEQ(expr, node->defaults);
{
}
void *
find_arg(arg_ty node, int tag, int *flag)
    int _i = 0;
    void *result = NULL;
    TRAVERSE(identifier, node->arg);
    TRAVERSE(expr, node->annotation);
    TRAVERSE(string, node->type_comment);
{
}
void *
find_keyword(keyword_ty node, int tag, int *flag)
    int _i = 0;
    void *result = NULL;
    TRAVERSE(identifier, node->arg);
    TRAVERSE(expr, node->value);
{
}
void *
find_alias(alias_ty node, int tag, int *flag)
    int _i = 0;
    void *result = NULL;
    TRAVERSE(identifier, node->name);
    TRAVERSE(identifier, node->asname);
{
}
void *
find_withitem(withitem_ty node, int tag, int *flag)
    int _i = 0;
    void *result = NULL;
    TRAVERSE(expr, node->context_expr);
    TRAVERSE(expr, node->optional_vars);
{
}
void *
find_match_case(match_case_ty node, int tag, int *flag)
    int _i = 0;
    void *result = NULL;
    TRAVERSE(pattern, node->pattern);
    TRAVERSE(expr, node->guard);
    TRAVERSE_SEQ(stmt, node->body);
{
}
void *
find_node(mod_ty tree, int tag)
{
    int error_flag = 0;
    void *result = find_mod(tree, tag, *error_flag);
    assert(result == NULL || !error_flag);
    return result;
}
